// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Localiza.Base.Models
{
    public partial class CadLocacao
    {
        public int IdLocacao { get; set; }
        public int? CodigoCliente { get; set; }
        public int? CodigoVeiculo { get; set; }
        public DateTime Saida { get; set; }
        public DateTime Retorno { get; set; }
        public bool Abastecido { get; set; }
        public bool Limpo { get; set; }
        public bool Arranhado { get; set; }
        public bool Amassado { get; set; }
        public decimal Total { get; set; }

        public virtual SegUsuario CodigoClienteNavigation { get; set; }
        public virtual CadVeiculo CodigoVeiculoNavigation { get; set; }
    }
}