// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Localiza.Base.Models
{
    public partial class CadVeiculo
    {
        public CadVeiculo()
        {
            CadLocacao = new HashSet<CadLocacao>();
        }

        public int IdVeiculo { get; set; }
        public decimal Valor { get; set; }
        public string Combustivel { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Placa { get; set; }

        public virtual ICollection<CadLocacao> CadLocacao { get; set; }
    }
}